@Library("Shared") _
pipeline{
    
    agent any 
    
    stages{
        
        stage("Hello"){
            steps{
                script{
                    hello()
                }
            }
        }
        stage("Cloning the code"){
            steps{
               script{
                clone("https://github.com/LondheShubham153/django-notes-app.git","main")
               }
                
            }
        }
        stage("Building the image"){
            steps{
                script{
                sh "docker build -t django-notes-app ."
                }
            }
        }
        stage("Deploy"){
            steps{
                echo "Deploying the code"
                sh "docker compose down && docker compose up -d"
            }
        }
    }
}
